export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SIGNIN="AUTH_SIGNIN";
export const AUTH_SIGNUP="AUTH_SIGNUP";
export const AUTH_SUBMIT_SUCCESS = "AUTH_SUBMIT_SUCCESS";
export const AUTH_SUBMIT_ERROR = "AUTH_SUBMIT_ERROR";
export const AUTH_SUBMIT_REDIRECT_PATH = "AUTH_SUBMIT_REDIRECT_PATH"

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
